name: main
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: |
          # Install dependency libraries according to the Ebiten official page.
          # https://ebiten.org/documents/install.html?os=linux
          sudo apt-get install -y libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
      - run: make setup
      - run: make lint
      - run: make check-generate
      - run: make test
      - run: make build
