name: main
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: |
          # Install dependency libraries according to the Ebiten official page.
          # https://ebitengine.org/en/documents/install.html?os=linux
          sudo apt-get update
          sudo apt install libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
      - run: make setup
      - run: make lint
      - run: make check-generate
      - run: make test
      - run: make build
