name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: make setup
      - run: make build VERSION=${GITHUB_REF#refs/tags/}
      - run: make zip VERSION=${GITHUB_REF#refs/tags/}
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          if echo ${{ github.ref }} | grep -q -e '-'; then PRERELEASE=-p; fi
          gh release create \
            -t "Release $VERSION" $PRERELEASE \
            -n "See [README.md](./README.md)." \
            "$VERSION" out/*.zip
